import { Injectable } from '@angular/core';
import {
  SuiviFinancement,
  SuiviFinancementDto,
} from '../models/suivi-financement';
import { Roles } from '../models/roles';
import { Statut_F } from '../models/financement';
import { SuiviFinancementsService } from '../services/suivi-financements.service';
import { HttpClient } from '@angular/common/http';
import { SpinnerService } from '../services/spinner.service';

@Injectable({
  providedIn: 'root',
})
export class SuiviFinancementsFakeService extends SuiviFinancementsService {
  constructor(http: HttpClient, spinnerSrv: SpinnerService) {
    super(http, spinnerSrv);
  }

  /**
   * Retourne suivi des financements v1 depuis fake data.
   */
  public async getAllVersion1(): Promise<SuiviFinancement[]> {
    const suiviFinancementsDto: SuiviFinancementDto[] = [
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.ATR,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 30000,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.SOLDE,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.ATR,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.ANTR,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.SOLDE,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
    ];
    return this.dtoToModel(suiviFinancementsDto);
  }

  /**
   * Retourne suivi des financements v2 depuis fake data.
   */
  public async getAllVersion2(
    annee1: number,
    annee2: number
  ): Promise<SuiviFinancement[]> {
    const suiviFinancementsDto: SuiviFinancementDto[] = [
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.SOLDE,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.ATR,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.ANTR,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.SOLDE,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
      {
        projet: {
          id_p: 4578,
          code_p: 2010,
          nom_p: 'CD conv xc',
          responsable: {
            id_u: 1020,
            prenom_u: 'Alexandre',
            nom_u: 'Perrin',
            email_u: 'Alexandre.Perrin@mail.fr',
            active_u: true,
            initiales_u: 'AP',
            roles: [Roles.Admin],
          },
          statut_p: false,
        },
        financement: {
          id_f: 5555,
          id_p: 4578,
          id_financeur: 9899,
          financeur: {
            id_financeur: 9899,
            nom_financeur: 'Financeur Z',
            ref_arret_attributif_financeur: 'ref A4',
          },
          montant_arrete_f: 250000,
          date_arrete_f: '10/12/2020',
          date_limite_solde_f: '10/12/2021',
          statut_f: Statut_F.SOLDE,
          date_solde_f: '10/12/2021',
          commentaire_admin_f: 'RAS',
          commentaire_resp_f: 'Ok',
          numero_titre_f: 'titre 45',
          annee_titre_f: 2019,
          imputation_f: 'imputation',
          solde: false,
        },
        recettes: {
          recettes_avant_annee_1: 50000,
          recettes_annee_1: 25000,
          recettes_annee_2: 5202120,
          recettes_annee_3: 10000,
          recettes_annee_4: 25000,
          recettes_apres_annee_4: 30000,
        },
      },
    ];

    return this.dtoToModel(suiviFinancementsDto);
  }
}
